ALTER TABLE PRODUCT DROP CONSTRAINT FK_PRODUCT_POSOLOGIE_ID
ALTER TABLE VENTE DROP CONSTRAINT FK_VENTE_CLIENT_ID
ALTER TABLE VENTE DROP CONSTRAINT FK_VENTE_OPERATOR_ID
ALTER TABLE VENTE DROP CONSTRAINT FK_VENTE_MEDECIN_ID
ALTER TABLE assurance_client DROP CONSTRAINT FK_assurance_client_CLIENT_ID
ALTER TABLE assurance_client DROP CONSTRAINT FK_assurance_client_ASSURANCE_ID
ALTER TABLE vente_produit DROP CONSTRAINT FK_vente_produit_VENTE_ID
ALTER TABLE vente_produit DROP CONSTRAINT FK_vente_produit_PRODUCT_ID
ALTER TABLE vente_produit DROP CONSTRAINT FK_vente_produit_SPECIFIQUE_ID
DROP TABLE ASSURANCE
DROP TABLE CLIENT
DROP TABLE MEDECIN
DROP TABLE PRODUCT
DROP TABLE OPERATOR
DROP TABLE VENTE
DROP TABLE assurance_client
DROP TABLE vente_produit
DROP TABLE POSOLOGIE
DROP TABLE posologie_specifique
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
