ALTER TABLE ADDRESS DROP CONSTRAINT FK_ADDRESS_id_client
ALTER TABLE ORDONNANCE DROP CONSTRAINT FK_ORDONNANCE_id_assurance
ALTER TABLE ORDONNANCE DROP CONSTRAINT FK_ORDONNANCE_id_medecin
ALTER TABLE ORDONNANCE DROP CONSTRAINT FK_ORDONNANCE_id_client
ALTER TABLE PRODUCT DROP CONSTRAINT FK_PRODUCT_id_ordonnance
ALTER TABLE client_assurance DROP CONSTRAINT FK_client_assurance_clients_ID
ALTER TABLE client_assurance DROP CONSTRAINT FK_client_assurance_assurances_ID
DROP TABLE ADDRESS
DROP TABLE ASSURANCE
DROP TABLE CLIENT
DROP TABLE MEDECIN
DROP TABLE ORDONNANCE
DROP TABLE PRODUCT
DROP TABLE client_assurance
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
