ALTER TABLE PRODUCT DROP CONSTRAINT FK_PRODUCT_POSOLOGIE_ID
ALTER TABLE VENTE DROP CONSTRAINT FK_VENTE_CLIENT_ID
ALTER TABLE VENTE DROP CONSTRAINT FK_VENTE_OPERATOR_ID
ALTER TABLE VENTE DROP CONSTRAINT FK_VENTE_MEDECIN_ID
ALTER TABLE assurance_client DROP CONSTRAINT FK_assurance_client_CLIENT_ID
ALTER TABLE assurance_client DROP CONSTRAINT FK_assurance_client_ASSURANCE_ID
ALTER TABLE vente_produit DROP CONSTRAINT FK_vente_produit_VENTE_ID
ALTER TABLE vente_produit DROP CONSTRAINT FK_vente_produit_PRODUCT_ID
ALTER TABLE vente_produit DROP CONSTRAINT FK_vente_produit_SPECIFIQUE_ID
DROP TABLE ASSURANCE CASCADE
DROP TABLE CLIENT CASCADE
DROP TABLE MEDECIN CASCADE
DROP TABLE PRODUCT CASCADE
DROP TABLE OPERATOR CASCADE
DROP TABLE VENTE CASCADE
DROP TABLE assurance_client CASCADE
DROP TABLE vente_produit CASCADE
DROP TABLE POSOLOGIE CASCADE
DROP TABLE posologie_specifique CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
